# File: ai_agent/agent/report.py
#
# Incident narrative report generator.
#
# Takes the structured incident JSON (same data written to incident_<ts>.json)
# and produces a human-readable Markdown report that a security analyst or
# executive can read without needing to parse raw machine data.
#
# Output protocol (consistent with main.py):
#   stdout → one JSON line: { "markdown": "<report text>" }
#             or           : { "error": "<message>" }

import json
import os
import sys
import datetime
from typing import Optional

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI

# ─── LLM config ───────────────────────────────────────────────────────────────

OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"
# Use a model with good narrative text generation (not JSON-mode only).
# gpt-4o-mini is cheap, fast, and writes clear prose.
REPORT_MODEL = "openai/gpt-4o-mini"


def _build_llm() -> ChatOpenAI:
    # Dedicated key for the report agent; falls back to the main key if not set.
    api_key = os.environ.get("OPENROUTER_REPORT_API_KEY") or os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        raise EnvironmentError(
            "Neither OPENROUTER_REPORT_API_KEY nor OPENROUTER_API_KEY is set. "
            "Add OPENROUTER_REPORT_API_KEY to ai_agent/.env."
        )
    return ChatOpenAI(
        model=REPORT_MODEL,
        base_url=OPENROUTER_BASE_URL,
        api_key=api_key,
        temperature=0.2,   # slight warmth for readable prose; 0 would be too dry
        max_tokens=2048,
        default_headers={
            "HTTP-Referer": "https://github.com/AegisAI",
            "X-Title":      "AegisAI Incident Reporter",
        },
    )


# ─── Prompts ──────────────────────────────────────────────────────────────────

_SYSTEM = """\
You are a senior cybersecurity analyst writing a formal incident report.
Your audience is a mix of technical responders and non-technical stakeholders,
with Section 7 written specifically for the SOC analyst who will act on the findings.

Rules:
- Write in clear, professional English — no jargon without explanation (except Section 7).
- Be specific: reference actual process names, IPs, file paths, and attack
  patterns from the data. Do NOT invent details not present in the input.
- Keep the Executive Summary to 3 sentences maximum.
- Use Markdown headings, bullet points, and tables where appropriate.
- Section 7 is for the SOC analyst only — use precise DFIR/SOC vocabulary,
  MITRE ATT&CK IDs, tool names (Volatility, Mimikatz, Sysmon, etc.), and
  one-sentence technical reasoning per action. Do not over-explain for non-technical readers here.
- Output ONLY the Markdown report — no preamble, no code fences around the
  whole document, no JSON.
"""

_HUMAN = """\
Generate a human-readable incident report from the following AegisAI detection data.
The data includes a "technical_suggestions" array — use these as the basis for Section 7, \
expanding each entry's keyword and reasoning into the structured format described in the template.

INCIDENT DATA:
{context}

---

Write the report using this exact structure:

# AegisAI Security Incident Report

**Report ID:** {report_id}
**Generated:** {generated_at}
**Severity:** {severity}

---

## 1. Executive Summary
[3 sentences maximum. What happened, how severe is it, and what was the immediate impact.]

## 2. Attack Timeline
[Describe the sequence of events as a narrative. Reference specific processes, \
attack patterns, and the critical path if present. Use bullet points for individual steps.]

## 3. Affected Systems & Indicators
[Table or bullet list of affected entities: process names with PIDs, suspicious \
network connections, malicious files. Include combined threat scores.]

## 4. MITRE ATT&CK Techniques Identified
[Bullet list of techniques detected. Pull from the attack chain patterns in the data. \
Map each to the MITRE tactic and ID provided.]

## 5. Containment Actions Taken
[List each action that was executed, its target, and whether it succeeded. \
If no actions were taken, state that clearly.]

## 6. Analyst Recommendations
[3–5 concrete next steps the security team should take. Be specific. \
Written for a mixed technical/executive audience.]

## 7. Technical Action Plan *(SOC Analyst)*
[3–5 MITRE-mapped technical actions for the hands-on analyst. \
Each item must follow this exact format:

**`<MITRE-ID> – <Short technique name>`** `[priority: critical|high|medium]`
> One sentence: what artefact to examine, which tool to use (e.g. Volatility, \
Mimikatz, Event Viewer, Sysmon, Wireshark, RECmd), and the specific indicator \
from this incident that makes this technique relevant.

Use only techniques that are directly evidenced by the incident data. \
Do not include generic recommendations not grounded in the data.]

---
*Report generated by AegisAI Automated Threat Analysis System*
"""

_PROMPT = ChatPromptTemplate.from_messages([
    ("system", _SYSTEM),
    ("human",  _HUMAN),
])


# ─── Context builder ──────────────────────────────────────────────────────────

def _build_context(incident: dict) -> dict:
    """
    Extract a lean, LLM-friendly summary from the full incident JSON.

    We drop the raw graph snapshot (nodes/edges list) and keep only the
    threat-relevant slice: attack chains, critical path narrative, a summary
    of threat entities, and actions taken.  This keeps the prompt under the
    practical token budget while giving the model all the signal it needs.
    """
    # Threat entities (nodes that are Malicious or Suspicious)
    nodes = incident.get("graph_snapshot", {}).get("nodes", [])
    threat_nodes = [
        {
            "label":          n.get("label"),
            "pid":            n.get("pid"),
            "threat_level":   n.get("threat_level"),
            "combined_score": round(float(n.get("combined_score", 0)), 3),
            "is_lolbin":      n.get("is_lolbin", False),
            "is_vector":      n.get("is_vector", False),
            "has_malicious_network": n.get("has_malicious_network", False),
            "has_malicious_memory":  n.get("has_malicious_memory", False),
            "has_malicious_file":    n.get("has_malicious_file", False),
        }
        for n in nodes
        if n.get("threat_level") in ("Malicious", "Critical", "Suspicious")
    ]

    # Attack chains with MITRE info
    attack_chains = incident.get("attack_chains", [])

    # Critical path narrative
    critical_path = incident.get("critical_path") or {}

    # Actions taken
    actions = incident.get("actions_taken", [])

    # Statistics
    stats = incident.get("statistics", {})

    # Also pull from the entities list if present (aggregated entity format)
    entities_raw = incident.get("entities", [])
    threat_entities_summary = [
        {
            "name":    e.get("name") or e.get("label"),
            "pid":     e.get("pid"),
            "score":   round(float(e.get("combined_score", 0)), 3),
            "level":   e.get("threat_level"),
        }
        for e in entities_raw
        if e.get("threat_level") in ("Malicious", "Critical", "Suspicious")
    ] if entities_raw else threat_nodes

    # Technical suggestions from the agent verdict (if the incident JSON includes them)
    technical_suggestions = incident.get("technical_suggestions", [])

    context = {
        "severity":               incident.get("severity", "Unknown"),
        "statistics":             stats,
        "attack_chains":          attack_chains,
        "critical_path_narrative": critical_path.get("narrative"),
        "critical_path_score":    critical_path.get("total_score"),
        "threat_entities":        threat_entities_summary,
        "actions_taken":          actions,
        "technical_suggestions":  technical_suggestions,
    }

    return context


# ─── Entry point ──────────────────────────────────────────────────────────────

def generate_report(incident: dict) -> str:
    """
    Generate a human-readable Markdown incident report.

    Args:
        incident: The structured incident dict (same data as incident_<ts>.json).

    Returns:
        A Markdown string ready to write to a .md file.

    Raises:
        EnvironmentError: OPENROUTER_API_KEY not set.
        ValueError: Empty or unparseable LLM response.
    """
    context      = _build_context(incident)
    context_json = json.dumps(context, indent=2)

    # Format a human-readable timestamp
    ts_raw = incident.get("generated_at")
    try:
        generated_at = datetime.datetime.fromtimestamp(
            int(ts_raw), tz=datetime.timezone.utc
        ).strftime("%Y-%m-%d %H:%M:%S UTC") if ts_raw else "Unknown"
    except Exception:
        generated_at = str(ts_raw) if ts_raw else "Unknown"

    report_id = incident.get("report_id", "N/A")
    severity  = incident.get("severity", "Unknown")

    llm    = _build_llm()
    chain  = _PROMPT | llm

    response = chain.invoke({
        "context":      context_json,
        "report_id":    report_id,
        "generated_at": generated_at,
        "severity":     severity,
    })

    # Extract text (handles str | list content blocks)
    content = response.content
    if isinstance(content, list):
        parts = []
        for block in content:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict):
                parts.append(block.get("text") or block.get("output_text") or "")
        content = "".join(parts)

    content = content.strip()
    if not content:
        raise ValueError("Report LLM returned empty content.")

    print(f"[report] Generated {len(content)} chars of Markdown.", file=sys.stderr)
    return content
